---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-appdaemon3"
  ADDON_SLUG: "appdaemon3"
  ADDON_TARGET: "appdaemon"

  ADDON_LEGACY_TAGS: "true"

  ADDON_AARCH64_BASE: "hassioaddons/base-python-aarch64:1.0.0"
  ADDON_AMD64_BASE: "hassioaddons/base-python-amd64:1.0.0"
  ADDON_ARMHF_BASE: "hassioaddons/base-python-armhf:1.0.0"
  ADDON_ARMV7_BASE: "hassioaddons/base-python-armv7:1.0.0"
  ADDON_I386_BASE: "hassioaddons/base-python-i386:1.0.0"
